name: 'Terraform Build Plan'

permissions:
  contents: read
  id-token: write
  pull-requests: write #tfcmt
  issues: write #tfcmt

on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      name: 'GCP Authentication'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - name: 'Terraform Install'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.9.2'

    - name: 'Install tfcmt'
      run: |
        wget https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.14.5/tfcmt_linux_amd64.tar.gz
        tar xvzf tfcmt_linux_amd64.tar.gz
        sudo mv tfcmt /usr/local/bin/

    - name: '설정 파일 생성'
      working-directory: ./terraform/build
      run: |
        printf "%s\n" "${{ secrets.TF_BUCKET }}" > backend.hcl
        printf "%s\n" "${{ secrets.TF_VARS }}" > terraform.tfvars

    - name: 'Terraform Plan'
      working-directory: ./terraform/build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo ""
        echo "*************** TERRAFORM PLAN ******************"
        echo "************************************************"
        echo ""
        terraform fmt
        cat backend.hcl
        cat terraform.tfvars
        terraform init -backend-config=backend.hcl
        tfcmt plan -patch -- terraform plan -no-color || exit 1
