name: 'Terraform Plan'

on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: 'Terraform Install'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.9.2'

    - name: 'Terraform Dev Plan'
      working-directory: ./terraform/main
      env:
        TF_WORKSPACE: dev
      run: |
        echo ""
        echo "*************** TERRAFOM PLAN ******************"
        echo "******* At environment: dev ********"
        echo "************************************************"
        echo ""
        terraform fmt -check -diff
        terraform init
        terraform plan || exit 1

    - name: 'Terraform Prd Plan'
      working-directory: ./terraform/main
      env:
        TF_WORKSPACE: prd
      run: |
        echo ""
        echo "*************** TERRAFOM PLAN ******************"
        echo "******* At environment: prd ********"
        echo "************************************************"
        echo ""
        terraform fmt -check -diff
        terraform init
        terraform plan || exit 1
