name: 'Terraform Plan'

permissions:
  contents: read
  id-token: write
  pull-requests: write #tfcmt

on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      name: 'GCP Authentication'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - name: 'Terraform Install'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.9.2'

    - name: 'Install tfcmt'
      run: |
        wget https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.14.5/tfcmt_linux_amd64.tar.gz
        tar xvzf tfcmt_linux_amd64.tar.gz
        sudo mv tfcmt /usr/local/bin/

    - name: 'Terraform Dev Plan'
      working-directory: ./terraform/main
      env:
        TF_WORKSPACE: dev
      run: |
        echo ""
        echo "*************** TERRAFOM PLAN ******************"
        echo "******* At environment: dev ********"
        echo "************************************************"
        echo ""
        terraform fmt -check -diff
        terraform init
        terraform plan -no-color | tfcmt plan

    - name: 'Terraform Prd Plan'
      working-directory: ./terraform/main
      env:
        TF_WORKSPACE: prd
      run: |
        echo ""
        echo "*************** TERRAFOM PLAN ******************"
        echo "******* At environment: prd ********"
        echo "************************************************"
        echo ""
        terraform fmt -check -diff
        terraform init
        tfcmt plan -patch -- terraform plan -no-color || exit 1
